global:
  scrape_interval: 15s  # Scrape metrics every 15 seconds

scrape_configs:
  # Scrape Prometheus metrics
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']  # Scrape Prometheus itself

  # Scrape Node Exporter metrics
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']  # Scrape Node Exporter metrics

  # Scrape Tendermint metrics (replace with your actual IP and port)
  - job_name: 'tendermint'
    metrics_path: /metrics  # Default metrics path
    static_configs:
      - targets: ['your_ip:port']  # Replace with the IP address and port of your Tendermint node
